
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|header|table|tr|div|style|script|ul|ol|form|dl))\b.*?&gt;|\{\{?(if|for|foreach|capture|case|literal|foreach|switch|section|while)|\{\s*$)</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|header|table|tr|div|style|script|ul|ol|form|dl))&gt;|\{\{?/(if|for|foreach|capture|case|literal|foreach|switch|section|while)|(^|\s)\})</string>
	<key>name</key>
	<string>eZ Publish</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\{)\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.tpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*(?=\})</string>
			<key>name</key>
			<string>comment.block.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(case|def|do|if|else|elseif|for|foreach|switch|section|set-block|set|while)\b</string>
			<key>name</key>
			<string>keyword.control.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(capture|config_load|counter|cycle|debug-accumulator|debug-log|debug-timing-point|debug-trace|eval|fetch|hash|include|insert|literal|match|math|strip_tags|rdelim|ldelim|assign|html_[a-z_]*)\b</string>
			<key>name</key>
			<string>support.function.built-in.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(eq|ne|gt|lt|gte|lte|not|even|odd|not|mod|div|by|as)\b</string>
			<key>name</key>
			<string>keyword.operator.other.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(upcase|downcase|count_characters|count_paragraphs|count_sentences|count_words|date_format|default|escape|indent|lower|nl2br|regex_replace|replace|spacify|string_format|strip_tags|strip|trim|upper|wordwrap)\b</string>
			<key>name</key>
			<string>support.function.variable-modifier.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z]+=</string>
			<key>name</key>
			<string>meta.attribute.tpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.tpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.tpl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.tpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.tpl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.tpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.tpl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.tpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.tpl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.tpl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\$)tpl\.</string>
			<key>name</key>
			<string>variable.other.tpl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.tpl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*?\b</string>
			<key>name</key>
			<string>variable.other.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true()|false())\b</string>
			<key>name</key>
			<string>constant.language.tpl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tpl</string>
	<key>uuid</key>
	<string>4D6BBA54-E3FC-4296-9CA1-662B2AD537C6</string>
</dict>
</plist>