<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tpl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>.*\{(section\s.|let.*|if\s.*|foreach.+\}|for.+\}|while.+\}|switch.+\}|cache-block.*\}|run-once.*\}|literal.*\}|delimiter.*\}).*</string>
	<key>foldingStopMarker</key>
	<string>.*\{\/(section|let|if|elseif|foreach|for|while|switch|cache-block|run-once|literal|delimiter)\}.*</string>
	<key>name</key>
	<string>eZ template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(as|def|else|elseif|foreach|if|switch|while|for|let|literal|section|section-else|undef)\b</string>
			<key>name</key>
			<string>keyword.control.tpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\$|`|"|\|\n)</string>
					<key>name</key>
					<string>constant.character.escape.tpl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.tpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escaped.untitled</string>
				</dict>
			</array>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append-block|attribute_view_gui|cache-block|case|def|do|if|else|elseif|for|foreach|node_view_gui|switch|section|set-block|set|undef|while)\b</string>
			<key>name</key>
			<string>keyword.control.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|begins_with|capture|concat|config_load|cycle|debug-accumulator|debug-log|debug-timing-point|debug-trace|expiry|ezcss_load|ezcss_require|ezini|ezscript_require|ezscript_load|fetch|first_set|hash|i18n|include|insert|is_array|is_boolean|is_class|is_float|is_integer|is_null|is_numeric|is_object|is_set|is_string|is_unset|literal|match|math|or|strip_tags|rdelim|ldelim|urlencode|html_[a-z_]*)\b</string>
			<key>name</key>
			<string>support.function.built-in.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(eq|ne|gt|lt|ge|le|null|not|even|odd|not|mod|div|by|as|max|offset|reverse|sequence)\b</string>
			<key>name</key>
			<string>keyword.operator.other.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|array|attribute|break|contains|continue|datetime|downcase|count|date_format|default|delimiter|explode|extract|ezhttp|ezhttp_hasvariable|ezimage|ezurl|ezroot|float|get_class|get_type|implode|indent|int|merge|nl2br|prepend|replace|simplify|skip|shorten|string_format|strip_tags|strip|trim|upcase|variable|wash|inc|sub|true|false)\b</string>
			<key>name</key>
			<string>support.function.variable-modifier.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z]+=</string>
			<key>name</key>
			<string>meta.attribute.tpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$+[a-zA-Z0-9\.-_\[\]:]*</string>
			<key>name</key>
			<string>variable.tpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{\*</string>
			<key>end</key>
			<string>\*}</string>
			<key>name</key>
			<string>comment.block.tpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{(literal)}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tpl</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.html.basic.literal.tpl</string>
			<key>end</key>
			<string>{/(literal)}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:style))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.css.embedded.html.tpl</string>
			<key>end</key>
			<string>&lt;/((?i:style))&gt;(?:\s*\n)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&gt;</string>
					<key>end</key>
					<string>(?=&lt;/(?i:style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.tpl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.tpl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$|\%)+[a-zA-Z0-9\.-_\[\]:]*</string>
					<key>name</key>
					<string>variable.tpl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tpl</string>
	<key>uuid</key>
	<string>D2F9659B-35E2-419A-BF40-068AC1F8275D</string>
</dict>
</plist>